### ISSUE TITLE
Selector of the level of issues to report

### ISSUE THREAD

**Issue by carlosmaroot** [Bort-Millipede/Burp-Batch-Report-Generator#3]
It would be nice to select the level of issues that you want to add on the report (**High, Medium, Low, Info, etc...**)

**Comment by Bort-Millipede** [comment]
Hi @carlosmaroot ! I realize you opened this issue a while ago, but I have added functionality to extension version 0.3 to filter reported issues by severity and/or confidence. Therefore I'm closing this issue as I believe it has been addressed.
